apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  selector:
    matchLabels:
      app: app1-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: app1-deployment
    spec:
      containers:
      - name: app1-deployment
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        env:
        - name: "PORT"
          value: "8080"